logging.level: warning
logging.files:
  rotateeverybytes: 10485760
  keepfiles: 2

filebeat:
  config_dir: /etc/filebeat/conf.d/

fields:
    Country: "US"
    Environment: "NONPROD"
fields_under_root: true
tags: ["filebeat"]

output.redis:
  hosts: ["pxy01-uslogs1.us.prod","pxy02-uslogs1.us.prod","pxy03-uslogs1.us.prod"]
  key: "%{[type]}"
  timeout: 5
