logging.level: warning
files.rotateeverybytes: 10485760
files.keepfiles: 2

filebeat:
  config_dir: /etc/filebeat/conf.d/

fields:
    Country: "KZ"
    Environment: "PROD"
fields_under_root: true
tags: ["filebeat"]

output.redis:
  hosts: ["elk-pilot.kz.prod"]
  key: "%{[type]}"
  timeout: 5
