logging.level: warning
files.rotateeverybytes: 10485760
files.keepfiles: 2

filebeat:
  config_dir: /etc/filebeat/conf.d/

fields:
    Country: "HCPDEV"
    Environment: "DEV"
fields_under_root: true
tags: ["filebeat"]

output.redis:
  hosts: ["logservice02.cz.nonprod", "logservice03.cz.nonprod"]
  key: "%{[type]}"
  timeout: 5
