logging.level: warning
files.rotateeverybytes: 10485760
files.keepfiles: 2

filebeat:
  config_dir: /etc/filebeat/conf.d/

fields:
    Country: "CS"
    Environment: "PROD"
fields_under_root: true
tags: ["filebeat"]

output.redis:
  hosts: ["elk01-czlogs1.cz.prod", "elk02-czlogs1.cz.prod"]
  key: "%{[type]}"
  timeout: 5
