logging.level: warning
files.rotateeverybytes: 10485760
files.keepfiles: 2

filebeat:
  config_dir: /etc/filebeat/conf.d/

fields:
    Country: "CN"
    Environment: "PROD"
fields_under_root: true

output.redis:
  hosts: ["scnvx040.prod.itc.homecredit.cn","scnvx041.prod.itc.homecredit.cn","scnvx042.prod.itc.homecredit.cn","scnvx043.prod.itc.homecredit.cn","scnvx044.prod.itc.homecredit.cn"]
  key: "%{[type]}"
  timeout: 5
