logging.level: warning
files.rotateeverybytes: 10485760
files.keepfiles: 2

filebeat:
  config_dir: /etc/filebeat/conf.d/

fields:
    Country: "VN"
    Environment: "PROD"
fields_under_root: true
tags: ["filebeat"]

output.redis:
  hosts: ["elk01-vnlogs1.vn.prod","elk02-vnlogs1.vn.prod"]
  key: "%{[type]}"
  timeout: 5
